const EveryPresident = [
  {
    id: "1",
    presidentPicture: "/pics/Deodoro_da_Fonseca.jpg",
    presidentLabel: "Deodoro da Fonseca",
    start_integer: "18891115",
  },
  {
    id: "2",
    presidentPicture: "/pics/Floriano_Peixoto.jpg",
    presidentLabel: "Floriano Peixoto",
    start_integer: "18911123",
  },
  {
    id: "3",
    presidentPicture: "/pics/Prudente_de_Morais.jpg",
    presidentLabel: "Prudente de Morais",
    start_integer: "18941115",
  },
  {
    id: "4",
    presidentPicture: "/pics/Manuel_Ferraz_de_Campos_Sales.jpg",
    presidentLabel: "Manuel Ferraz de Campos Sales",
    start_integer: "18981115",
  },
  {
    id: "5",
    presidentPicture: "/pics/Francisco_de_Paula_Rodrigues_Alves.jpg",
    presidentLabel: "Francisco de Paula Rodrigues Alves",
    start_integer: "19021115",
  },
  {
    id: "6",
    presidentPicture: "/pics/Afonso_Pena.jpg",
    presidentLabel: "Afonso Pena",
    start_integer: "19061115",
  },
  {
    id: "7",
    presidentPicture: "/pics/Nilo_Peçanha.jpg",
    presidentLabel: "Nilo Peçanha",
    start_integer: "19090614",
  },
  {
    id: "8",
    presidentPicture: "/pics/Hermes_da_Fonseca.jpg",
    presidentLabel: "Hermes da Fonseca",
    start_integer: "19101115",
  },
  {
    id: "9",
    presidentPicture: "/pics/Venceslau_Brás.jpg",
    presidentLabel: "Venceslau Brás",
    start_integer: "19141115",
  },
  {
    id: "10",
    presidentPicture: "/pics/Delfim_Moreira.jpg",
    presidentLabel: "Delfim Moreira",
    start_integer: "19181115",
  },
  {
    id: "11",
    presidentPicture: "/pics/Epitácio_Pessoa.jpg",
    presidentLabel: "Epitácio Pessoa",
    start_integer: "19190728",
  },
  {
    id: "12",
    presidentPicture: "/pics/Artur_Bernardes.jpg",
    presidentLabel: "Artur Bernardes",
    start_integer: "19221115",
  },
  {
    id: "13",
    presidentPicture: "/pics/Washington_Luís.jpg",
    presidentLabel: "Washington Luís",
    start_integer: "19261115",
  },
  {
    id: "14",
    presidentPicture: "/pics/Junta_Governativa_Provisória.png",
    presidentLabel: "Junta Governativa Provisória",
    start_integer: "19301024",
  },
  {
    id: "15",
    presidentPicture: "/pics/Getúlio_Vargas.jpg",
    presidentLabel: "Getúlio Vargas (1° Mandato)",
    start_integer: "19301103",
  },
  {
    id: "16",
    presidentPicture: "/pics/José_Linhares.jpg",
    presidentLabel: "José Linhares",
    start_integer: "19451029",
  },
  {
    id: "17",
    presidentPicture: "/pics/Eurico_Gaspar_Dutra.jpg",
    presidentLabel: "Eurico Gaspar Dutra",
    start_integer: "19460131",
  },
  {
    id: "18",
    presidentPicture: "/pics/Getúlio_Vargas_2.jpg",
    presidentLabel: "Getúlio Vargas (2° Mandato)",
    start_integer: "19510131",
  },
  {
    id: "19",
    presidentPicture: "/pics/Café_Filho.jpg",
    presidentLabel: "Café Filho",
    start_integer: "19540824",
  },
  {
    id: "20",
    presidentPicture: "/pics/Carlos_Luz.jpg",
    presidentLabel: "Carlos Luz",
    start_integer: "19551109",
  },
  {
    id: "21",
    presidentPicture: "/pics/Nereu_Ramos.jpg",
    presidentLabel: "Nereu Ramos",
    start_integer: "19551111",
  },
  {
    id: "22",
    presidentPicture: "/pics/Juscelino_Kubitschek.jpg",
    presidentLabel: "Juscelino Kubitschek",
    start_integer: "19560131",
  },
  {
    id: "23",
    presidentPicture: "/pics/Jânio_Quadros.png",
    presidentLabel: "Jânio Quadros",
    start_integer: "19610131",
  },
  {
    id: "24",
    presidentPicture: "/pics/João_Goulart.jpg",
    presidentLabel: "João Goulart",
    start_integer: "19610908",
  },
  {
    id: "25",
    presidentPicture: "/pics/Pascoal_Ranieri_Mazzilli.jpg",
    presidentLabel: "Pascoal Ranieri Mazzilli",
    start_integer: "19640402",
  },
  {
    id: "26",
    presidentPicture: "/pics/Humberto_Castelo_Branco.jpg",
    presidentLabel: "Humberto Castelo Branco",
    start_integer: "19640415",
  },
  {
    id: "27",
    presidentPicture: "/pics/Artur_da_Costa_e_Silva.jpg",
    presidentLabel: "Artur da Costa e Silva",
    start_integer: "19670315",
  },
  {
    id: "28",
    presidentPicture: "/pics/Junta_militar_brasileira_de_1969.png",
    presidentLabel: "Ditadura Militar",
    start_integer: "19690831",
  },
  {
    id: "29",
    presidentPicture: "/pics/Emílio_Garrastazu_Médici.jpg",
    presidentLabel: "Emílio Garrastazu Médici",
    start_integer: "19691030",
  },
  {
    id: "30",
    presidentPicture: "/pics/Ernesto_Geisel.png",
    presidentLabel: "Ernesto Geisel",
    start_integer: "19740315",
  },
  {
    id: "31",
    presidentPicture: "/pics/João_Figueiredo.jpg",
    presidentLabel: "João Figueiredo",
    start_integer: "19790315",
  },
  {
    id: "32",
    presidentPicture: "/pics/José_Sarney.jpg",
    presidentLabel: "José Sarney",
    start_integer: "19850315",
  },
  {
    id: "33",
    presidentPicture: "/pics/Fernando_Collor_de_Mello.jpg",
    presidentLabel: "Fernando Collor de Mello",
    start_integer: "19900315",
  },
  {
    id: "34",
    presidentPicture: "/pics/Itamar_Franco.jpg",
    presidentLabel: "Itamar Franco",
    start_integer: "19921229",
  },
  {
    id: "35",
    presidentPicture: "/pics/Fernando_Henrique_Cardoso.jpg",
    presidentLabel: "Fernando Henrique Cardoso",
    start_integer: "19950101",
  },
  {
    id: "36",
    presidentPicture: "/pics/Luiz_Inácio_Lula_da_Silva.jpg",
    presidentLabel: "Luiz Inácio Lula da Silva (1° Mandato)",
    start_integer: "20030101",
  },
  {
    id: "37",
    presidentPicture: "/pics/Dilma_Rousseff.jpg",
    presidentLabel: "Dilma Rousseff",
    start_integer: "20110101",
  },
  {
    id: "38",
    presidentPicture: "/pics/Michel_Temer.jpg",
    presidentLabel: "Michel Temer",
    start_integer: "20160831",
  },
  {
    id: "39",
    presidentPicture: "/pics/Jair_Bolsonaro.jpg",
    presidentLabel: "Jair Bolsonaro",
    start_integer: "20190101",
  },
  {
    id: "40",
    presidentPicture: "/pics/Luiz_Inácio_Lula_da_Silva_2.jpg",
    presidentLabel: "Luiz Inácio Lula da Silva (2° Mandato)",
    start_integer: "20230101",
  },
];

export default EveryPresident;
